name: kedro_base
channels:
  - defaults
  - conda-forge
  - "file:////aemo.local/data/Departments/WA/WA System Management/Power Systems/Repository/conda_channel"
dependencies:
#  - python=3.10.12
  - python=3.9.17
  - pandas
  - jupyter
  - ipykernel
  - cx_oracle
  - aemo-pi #from file:////aemo.local/data/Departments/WA/WA System Management/Power Systems/Repository/conda_channel
  - kedro
  #  - kedro-airflow
  #  - kedro-neptune
  - pip
  - pip:
    - find-kedro
    - kedro-mlflow
    - kedro-datasets
    - kedro-viz
    - git+https://norvbgit1.aemo.local/PSMP/WA_db.git@master#egg=WA-db
#    - kedro-docker
#    - kedro-accelerator
